
service: hello-world

provider:
  name: aws
  runtime: python3.7
  region: ap-southeast-1
  
  
custom:
  pythonRequirements:
    dockerizePip: true
package:
  individually: false
  exclude:
    - package.json
    - package-log.json
    - node_modules/**


functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          request:
            template:
              application/json: {
                  "type" : "$input.params().querystring.get('type')",
                }



plugins:
  - serverless-python-requirements
